### ISSUE TITLE
Doc fails to build with sphinx 1.3

### ISSUE THREAD

**Issue by sbraz** [JonnyJD/python-discid#45]
Hi, could you make the doc build with more recent versions of sphinx?
```
Running Sphinx v1.3.5
making output directory...

Extension error:
Could not import extension ext.data_doc (exception: cannot import name 'safe_repr')
```
Apparently `safe_repr` was replaced by `object_description` but I'm not even sure the `data_doc extension` is needed (I tried building with a fixed extension and without the extension and the doc seems identical).

**Comment by sbraz** [comment]
My bad, it's fixed in git but not in the latest release. I didn't notice https://github.com/JonnyJD/python-discid/commit/fd714adc2d34b3b661b64cda53190b42a33d1670
